config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :friendships
  resources :categories
  resources :friend_requests, only: [:create, :update]
  resources :conversations
  resources :messages
  resources :badges
  resources :accountabuddy_requests, only:[:create, :update]
  resources :user_categories
  resources :recommendations, only:[:create, :new]
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  root 'users#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: :friend_id
  has_many :inverse_friends, :through => :inverse_friendships, source: :user
  has_many :user_categories
  has_many :friend_requests
  has_many :categories, :through => :user_categories
  has_many :conversations, foreign_key: :sender_id
  has_many :conversations, foreign_key: :recipient_id
  has_many :badges
  has_many :accountabuddy_requests
  has_many :recommendations

  has_secure_password

  geocoded_by :address
  mount_uploader :attachment
  after_validation :reverse_geocode
  validates_length_of :password, :in => 6..20
  validates_presence_of :name, :username, :email, :password
  validates_uniqueness_of :username, :email
  # after_validation :geocode, :if => :address_changed?


  def self.create_with_omniauth(auth)
    user = find_or_create_by(uid: auth['uid'], provider: auth['provider'])

      user.email = "#{auth['uid']}@#{auth['provider']}.com"
      user.password = auth['uid']
      user.name = auth['info']['name']
      user.gender = auth['extra']['raw_info']['gender']


      if User.exists?(user)
        user
      else
        user.save!
          badge1 = Badge.new(name: "Fitness", description: "You're a fitness superstar!", user_id: user.id, badge_image_link: "fitness-badge.png")
          badge2 = Badge.new(name: "Diet", description: "You're a Diet superstar!", user_id: user.id, badge_image_link:"diet-badge.png")
          badge3 = Badge.new(name: "Hobbies", description: "You're a Hobbies superstar!", user_id: user.id, badge_image_link:"hobbies-badge.png")
          badge4 = Badge.new(name: "Education", description: "You're a Education superstar!", user_id: user.id, badge_image_link:"education-badge.png")
          badge1.save && badge2.save && badge3.save && badge4.save
        user
      end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update]
  before_filter :get_mapbox_token, only: [:new, :edit]

  def index
    if params[:search].present?
      @users = User.near(params[:search], 25)
    else
      @users = User.all
    end

    respond_to do |format|
      format.html
      format.json { render json: @geojson }
    end
  end

  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      create_badges_for_user
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      flash[:error] = "Signup was unsuccessful. Please try again."
      redirect_to '/signup'
    end
  end

  def show
    @badges = @user.badges
    @recommendations = Recommendation.where(recipient_id: @user.id)
    @user_categories = UserCategory.where(user_id: @user.id)
    
    fetch_friends
    fetch_friend_requests
    search_for_friendship
  end

  def edit
    if current_user == @user
      @user
    else
      flash[:error] = "You cannot edit a different user's account!!"
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user.update(user_params)

    if @user.save
      redirect_to user_path(@user.id)
    else
      flash[:error] = "Update was not successful. Please try again."
      redirect_to edit_user_path(@user.id)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :username,
      :email,
      :password,
      :password_confirmation,
      :latitude,
      :longitude,
      :about_me,
      :gender,
      :attachment
    )
  end
  
  def load_user
    @user = User.find(params[:id])
  end

  def fetch_friend_requests
    @friend_requests = FriendRequest.where(recipient_id: @user.id, friends: false)
    @pending_requests = FriendRequest.where(user_id: @user.id, friends:false)
    @accountabuddy_requests = AccountabuddyRequest.where(recipient_id: @user.id)
  end

  def fetch_friends
    @accountabuddies = @user.friendships.where(accountabuddy:true)
    @just_friends = @user.friendships.where(accountabuddy:false)
  end

  def search_for_friendship
    if @user.id != current_user.id
      if Friendship.find_by(user_id: current_user.id , friend_id: @user.id)
        @friendship = Friendship.find_by(user_id: current_user.id , friend_id: @user.id)
        @accountabuddy_relationship = @friendship.accountabuddy
        @inverse_friendship = Friendship.find_by(friend_id: current_user.id, user_id: @user.id)
        @inverse_accountabuddy_relationship = @inverse_friendship.accountabuddy
      end
    end    
  end

  def create_badges_for_user
    @badge1 = Badge.create(name: "Fitness", description: "You're a fitness superstar!", user_id: @user.id, badge_image_link: "fitness-badge.png")
    @badge2 = Badge.create(name: "Diet", description: "You're a Diet superstar!", user_id: @user.id, badge_image_link:"diet-badge.png")
    @badge3 = Badge.create(name: "Hobbies", description: "You're a Hobbies superstar!", user_id: @user.id, badge_image_link:"hobbies-badge.png")
    @badge4 = Badge.create(name: "Education", description: "You're a Education superstar!", user_id: @user.id, badge_image_link:"education-badge.png")
  end

  def get_mapbox_token
    @mapbox_token = ENV['MAPBOX_TOKEN']
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_to_profile.html.erb
<h1 style="font-size:4em">Add to Your Profile</h1>

    <%= flash[:error] %>


      <div class="row">

        <div id="user-signedit-form" class="large-12">
          <%= form_for :user, method: :put, url: user_path(current_user.id) do |f| %>

            <div class="row">
              <div class="large-8 columns"><%= f.hidden_field :name, value: current_user.name %>
              </div>
            </div>

            <div class="row">
              <div class="large-8 columns"><%= f.hidden_field :username, value: current_user.name %>
              </div>
            </div>

             <div class="row">
              <div class="large-8 columns"><%= f.hidden_field :email, value: current_user.email %>
              </div>
            </div>

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Upload Profile Picture</label>
              </div>
              <div class="large-8 columns"><%= f.file_field :attachment %>
              </div>
            </div>
            

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Tell us about your goals: </label>
              </div>
              <div class="large-8 columns">
            <div id="new-user-description"><%= f.text_area :about_me %></div>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Gender:</label>
              </div>
              <div class="large-8 columns"><%= f.select :gender, ['Female', 'Male']%>
              </div>
            </div>

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Latitude:</label>
              </div>
              <div class="large-8 columns" id="latitude-fill"><%= f.text_field :latitude %>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Longitude:</label>
              </div>
              <div class="large-8 columns" id="longitude-fill"><%= f.text_field :longitude %>
              </div>
            </div>         

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right"></label>
              </div>
              <div class="large-8 columns" id="longitude-fill"><%= render 'map_show' %>
              </div>
            </div>             


             <div class="row">
              <div class="large-8 columns"><%= f.hidden_field :password, value: current_user.password %>
              </div>
            </div>

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right"></label>
              </div>
              <div class="large-8 columns"> <%= f.hidden_field :password_confirmation, value: current_user.password %>
              </div>
            </div>


            <%= f.submit "Add", :class => "myButton" %>
        

          <% end %>
        </div>
      </div>

app/views/users/_location_all.html.erb
<h1>All User Locations</h1>
<%= form_tag user_path, :method => :get do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search Near", :name => nil %>
	</p>
<% end %>
<table>
	<tr>
		<th>Username</th>
		<th>Address</th>
		<th>Latitude</th>
		<th>Longitude</th>
	</tr>
	<% for user in @users %>
	<tr>
		<td><%= user.username %></td>
		<td><%= user.address %></td>
		<td><%= user.latitude %></td>
		<td><%= user.longitude %></td>
	</tr>
	<% end %>
</table>

app/views/users/_location_show.html.erb
<h1>Location</h1>	
<p>Address: <%= @user.address %></p>
<p>Latitude: <%= @user.latitude %></p>
<p>Longitude: <%= @user.longitude %></p>

<h3>Nearby friends</h3>
<ul>
	<% for user in @user.nearbys(10) %> 
		<li><%= link_to user.address, user.username %> (<%= user.distance.round(2) %> miles)</li>
	<% end %>
</ul>

app/views/users/_map_index.html.erb
<!-- MAPBOX FIND ALL-->
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8 />
  <title>Geolocation</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <script src='https://api.mapbox.com/mapbox.js/v2.2.3/mapbox.js'></script>
  <link href='https://api.mapbox.com/mapbox.js/v2.2.3/mapbox.css' rel='stylesheet' />
  <style>
    body { margin:0; padding:0; }
    #map { position:absolute; top:0; bottom:0; width:100%; }
  </style>
</head>
<body>

<div id='map'></div>
<script>
L.mapbox.accessToken = "<%= ENV['MAPBOX_TOKEN'] %>";
var geolocate = document.getElementById('geolocate');
var map = L.mapbox.map('map', 'mapbox.streets');
var myLayer = L.mapbox.featureLayer().addTo(map);

var geoJson = [];
<% @users.each do |user| %>
      geoJson.push({
      type: 'Feature',
      geometry: {
      type: 'Point',
      coordinates: [<%= user.longitude %>, <%= user.latitude %>]
      },
      properties: {
        'marker-color': '#00607d',
        'marker-symbol': 'circle',
        'marker-size': 'medium'
      }
    });
<% end %>


// Add custom popups to each using our custom feature properties
myLayer.on('layeradd', function(e) {
  var marker = e.layer,
  feature = marker.feature;
    // Create custom popup content
    var popupContent =  '<a target="_blank" class="popup" href="' + feature.properties.url + '">' +
    '<img src="' + feature.properties.image + '" />' +
    feature.properties.city +
    '</a>';
    // http://leafletjs.com/reference.html#popup
    marker.bindPopup(popupContent,{
      closeButton: true,
      minWidth: 320
    });
  });
// Add features to the map
myLayer.setGeoJSON(geoJson);
myLayer.on('mouseover', function(e) {
  e.layer.openPopup();
  console.log('sex')
});

</script>
</body>
</html>

app/views/users/_map_show.html.erb
<!-- MAPBOX Shows 1-->
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8 />
  <title>Geolocation</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <script src='https://api.mapbox.com/mapbox.js/v3.0.1/mapbox.js'></script>
  <link href='https://api.mapbox.com/mapbox.js/v3.0.1/mapbox.css' rel='stylesheet' />
  <style>
    body { margin:0; padding:0; }
    #map { position:absolute; top:1%; bottom:0; width:1%; height:1%; }
  </style>
</head>
<body>
<div id='map'></div>
<a href='#' id='geolocate'>Find My Location</a>
<script>
L.mapbox.accessToken = '<%= @mapbox_token %>'
var geolocate = document.getElementById('geolocate');
var map = L.mapbox.map('map', 'mapbox.streets');
var myLayer = L.mapbox.featureLayer().addTo(map);
if (!navigator.geolocation) {
    geolocate.innerHTML = 'Geolocation is not available';
} else {
    geolocate.onclick = function (e) {
        e.preventDefault();
        e.stopPropagation();
        map.locate();
        console.log(e);
    };
}
// Once we've got a position, zoom and center the map on it, and add a single marker.
map.on('locationfound', function(e) {
    map.fitBounds(e.bounds);
    myLayer.setGeoJSON({
        type: 'Feature',
        geometry: {
            type: 'Point',
            coordinates: [e.latlng.lng, e.latlng.lat]
        },
        properties: {
            'title': 'Here I am!',
            'marker-color': '#ff8888',
            'marker-symbol': 'star'
        }
    });
    // And hide the geolocation button
    geolocate.parentNode.removeChild(geolocate);
    // fill in form with latitude and longitude
    $('.latitude-val').val(e.latlng.lat);
    $('.longitude-val').val(e.latlng.lng);
});
// If the user chooses not to allow their location to be shared, display an error message.
map.on('locationerror', function() {
    geolocate.innerHTML = 'Position could not be found';
});
</script>
</body>
</html>

app/views/users/_sign_in.html.erb
<%= form_tag '/login' do %>

  Email: <%= text_field_tag :email %>
  Password: <%= password_field_tag :password %>
  <%= submit_tag "Submit" %>

<% end %>

app/views/users/_user_index_header.html.erb
<% if current_user %>
  <p id="nav-bar-user-signedin">
  	Signed in as <%= current_user.name%> 
  	<%=link_to "Profile", user_path(current_user.id) %> | <%= link_to "Logout", '/logout' %>
  </p>
<% else %>
  <p class="nav-bar-user">
  	<%= link_to 'Login', '/login', id: 'login-link' %> | <%= link_to 'Signup', '/signup' %>
	  </p>
<% end %>

app/views/users/edit.html.erb
<%= render 'layouts/navigation' %>
<div class="user-signedit-container">
	<div class="user-signedit-box">

    <% if current_user.latitude == nil %>


      <%= render 'users/add_to_profile' %>


    <% else %>
    <h1>Edit Your Profile</h1>

    <%= flash[:error] %>


      <div class="row">

        <div id="user-signedit-form" class="large-12">
          <%= form_for :user, method: :put, url: user_path(current_user.id) do |f| %>

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">First name:</label>
              </div>
              <div class="large-8 columns"><%= f.text_field :name %>
              </div>
            </div>

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Username:</label>
              </div>
              <div class="large-8 columns"><%= f.text_field :username %>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Email:</label>
              </div>
              <div class="large-8 columns"><%= f.text_field :email %>
              </div>
            </div>

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Upload Profile Picture</label>
              </div>
              <div class="large-8 columns"><%= f.file_field :attachment %>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Tell us about your goals: </label>
              </div>
              <div class="large-8 columns">
            <div id="new-user-description"><%= f.text_area :about_me %></div>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Gender:</label>
              </div>
              <div class="large-8 columns"><%= f.select :gender, ['Female', 'Male']%>
              </div>
            </div>


            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Latitude:</label>
              </div>
              <div class="large-8 columns" id="latitude-fill">
              <%= f.text_field :latitude, class: 'latitude-val'%>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Longitude:</label>
              </div>
              <div class="large-8 columns" id="longitude-fill">
              <%= f.text_field :longitude, class: 'longitude-val'%>
              </div>
            </div>         

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right"></label>
              </div>
              <div class="large-8 columns"><%= render 'map_show' %>
              </div>
            </div> 

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Password:</label>
              </div>
              <div class="large-8 columns">       <%= f.password_field :password %>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Password Confirmation:</label>
              </div>
              <div class="large-8 columns"> <%= f.password_field :password_confirmation %>
              </div>
            </div>

            <%= f.submit "Update", :class => "myButton" %>

          <% end %>
        </div>
      </div>
      <% end %>

	</div>
</div>

app/views/users/index.html.erb
<div id="home-page">
		<div class="cover">
			<p class="nav-bar-home"><%= link_to "AccountaBuddy", '/'%></p>
			<div id="user-show-login-signup" >
				<%= render 'user_index_header' %>
					<div id="splash-box-1">
						<%= flash[:error] %>
					

				
						<%= form_tag '/login' do %>

						  Email: <%= text_field_tag :email %>
						  Password: <%= password_field_tag :password %>
						  <%= submit_tag "Submit", :class => "myButton" %>


						<% end %>
						<img id="facebook-button" src="<%= asset_path( 'fb-logo.png' ) %>">
						<%= link_to "Sign in with Facebook", "/auth/facebook" %>
						

						</img>
		
					</div>
				</div>
				<img src="<%= asset_path( 'gg-splash.jpg' ) %>">
		</div>
		<div class="cover">
			<img class="splash-image" src="<%= asset_path( 'white-splash.jpg' ) %>">
		</div>
		<div class="cover">
			<img class="splash-image" src="<%= asset_path( 'shoe-splash-2.jpg' ) %>">
		</div>
		<div class="cover">
			<img class="splash-image" src="<%= asset_path( 'orange-splash.jpg' ) %>">
		</div>
		<div class="cover">
			<img class="splash-image" src="<%= asset_path( 'paddleboarding-splash.jpg' ) %>">
		</div>
		<div class="cover">
			<img class="splash-image" src="<%= asset_path( 'teal-splash.jpg' ) %>">
		</div>
		<div class="cover">
			<img class="splash-image" src="<%= asset_path( 'teens-splash.jpg' ) %>">
		</div>
</div>

app/views/users/new.html.erb
<div class="user-signedit-container">
  <h1><%= link_to "AccountaBuddy", '/'%></h1>
	<div class="user-signedit-box">

		<h2>Sign Up</h2>

      <div class="row">
        <div id="user-signedit-form" class="large-12">

          <%= form_for :user, url: '/users' do |f| %>

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">First name:</label>
              </div>
              <div class="large-8 columns"><%= f.text_field :name %>
              </div>
            </div>

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Username:</label>
              </div>
              <div class="large-8 columns"><%= f.text_field :username %>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Email:</label>
              </div>
              <div class="large-8 columns"><%= f.text_field :email %>
              </div>
            </div>

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Upload Profile Picture</label>
              </div>
              <div class="large-8 columns"><%= f.file_field :attachment %>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">In three sentences or less: Who are you, and what are you working toward? </label>
              </div>
              <div class="large-8 columns"><div id="new-user-description"><%= f.text_area :about_me %></div>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Gender:</label>
              </div>
              <div class="large-8 columns"><%= f.select :gender, ['Female', 'Male']%>
              </div>
            </div>    

            <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Latitude:</label>
              </div>
              <div class="large-8 columns" id="latitude-fill">
              <%= f.text_field :latitude, class: 'latitude-val'%>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Longitude:</label>
              </div>
              <div class="large-8 columns" id="longitude-fill">
              <%= f.text_field :longitude, class: 'longitude-val'%>
              </div>
            </div>         

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right"></label>
              </div>
              <div class="large-8 columns"><%= render 'map_show' %>
              </div>
            </div>                  

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Password:</label>
              </div>
              <div class="large-8 columns"><%= f.password_field :password %>
              </div>
            </div>

             <div class="row">
              <div class="large-4 columns"><label for="right-label" class="right">Password Confirmation:</label>
              </div>
              <div class="large-8 columns"> <%= f.password_field :password_confirmation %>
              </div>
            </div>

            <%= f.submit "Submit", :class => "myButton" %>

          <% end %>
        </div>
      </div>

	</div>
  <p>Already a user? <span id="signup"><%= link_to 'Log in', '/login' %></span></p>
</div>

app/views/users/show.html.erb
<%= render 'layouts/navigation' %>
  <div class="row">
    <div class="large-4 columns" style="text-align: left">
      <img class="profile-image" src="<%=@user.attachment%>">
    </div>
    <div class="large-8 columns">
    <%= flash[:error] %>
      <% if @user == current_user  %>
        <p id="user-show-header">Hello <%= @user.name %>!</p>
        <p id="user-show-header-2"> What goals will you vanquish today?<p>
      <% else %>
        <p id="user-show-header"><%= @user.name %></p>
      <% end %>
        <div class="row">
          <ul class="large-block-grid-4" id="user-badges">


            <% if current_user %>
              <% if @accountabuddy_relationship == true %>
               <% @badges.order(:id).each do |badge| %>
                  <li> <img class="badge-image" src="<%= asset_path(badge.badge_image_link) %>">
                  <p> <%= badge.points %> victories</p>
                      <%= link_to "Endorse!", badge_path(badge.id), method: 'put', class: "endorse-link" %>
                  </li>
                <% end %>
              <% elsif @inverse_accountabuddy_relationship %>
                   <% @badges.order(:id).each do |badge| %>
                  <li> <img class="badge-image" src="<%= asset_path(badge.badge_image_link) %>">
                  <p> <%= badge.points %> victories</p>
                      <%= link_to "Endorse!", badge_path(badge.id), method: 'put', class: "endorse-link" %>
                  </li>
                <% end %>
              <% else %>
                <% @badges.order(:id).each do |badge| %>
                  <li> <img class="badge-image" src="<%= asset_path(badge.badge_image_link) %>">
                  <p> <%= badge.points %> victories</p>
                  </li>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
<div class="innards">

<div class="row">
  <div id="user-show-about" class="large-7 columns">

            <div class="quote">
              <span id="speech-mark-left">&ldquo;</span>
              <%= @user.about_me %>
              <span id="speech-mark-right">&rdquo;</span>
            </div>

  </div>
  <div id="user-show-categories" class="large-5 columns">
      <% if @user == current_user  %>
      <p id="user-show-categories-current">Current goals:</p>
      <% @user_categories.each do |category| %>
       <%= link_to category.category.name, category_path(category.category.id) %>

      <% end %>
      <p id="user-show-categories-new"><%= link_to "Start a new goal", categories_path %></p>
      <% end %>
  </div>
</div>
<div id="user-show-praise-container" class="row">
  <div id="user-show-praise" class="large-12 columns">
        <h3>Recommendations</h3>
     <div class="row">
      <div class="large-2 columns">
      </div>
      <div class="large-10 columns">

        <table style="border-style:none" id="recommendation-append">
            <% @recommendations.each do |recommendation| %>
          <tr >
              <td style="float:left"><img  src="<%= recommendation.user.attachment%>"></td>
              <td style="width:80%">
                <div id="recommendation-text">
                  "<%= recommendation.body %>"
                  <br>
                  - <%= recommendation.user.name %>
                </div>
              </td>
          </tr>

            <% end %>
        </table>

          <% if current_user %>
            <% if @accountabuddy_relationship || @inverse_accountabuddy_relationship %>
            <%= link_to "Write a Recommendation!", recommendations_path, id: "recommendation-link" %>
              <div id="recommendation-box">
                Your Recommendation:
                <%= form_for :recommendation, url: '/recommendations', id: "recommendation-form" do |f| %>
                <%= f.text_field :body %>
                <%= f.hidden_field :recipient_id, value: @user.id %>
                <%= f.button "Submit", :class => "myButton" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
      </div>
     </div>
    <p>
  </div>
</div>
<% if @user == current_user %>
  <div class="row">
    <div id="user-show-friends" class="large-5 columns">

      <h2>Your Friends</h2>
        <ul>
          <% @just_friends.each do |friendship| %>
              <%= link_to friendship_path(friendship.id) do%>
                 <li><%= friendship.friend.name %> : <%=friendship.category.name %></li>
              <% end %>
          <% end %>
        </ul>
        <div class="row">
          <div class="large-12 columns">
             <p class="pending-sent">Pending Friend Requests You've Sent</p>
            <ul>
              <% @pending_requests.each do |pending_request| %>
               <li><%= pending_request.recipient.name %></li>
              <% end %>
            </ul>
            <div class="large-12 columns">
              <p class="pending-sent">Friend Requests Awaiting Your Approval</p>
                  <% @friend_requests.each do |friend_request| %>
                    <ul>
                    <li><%= friend_request.user.name %></li>
                      <%= form_tag friend_request_path(friend_request.id), method: 'put' do %>
                      <%= submit_tag "Accept", :class => "mySmallButton" %>
                    <% end %>
                  <% end %>
                  </ul>
            </div>
        </div>
    </div>
  </div>
    <div id="user-show-accountabuddies" class="large-7 columns">

    <h2>Your AccountaBuddies </h2>
      <ul>
        <% @accountabuddies.each do |accountabuddy| %>
              <%= link_to friendship_path(accountabuddy.id) do%>
                <li><%= accountabuddy.friend.name %>: <%= accountabuddy.category.name %></li>
              <% end %>
        <% end %>
      </ul>
      <ul>
        <p> AccountaBuddy Requests Awaiting Your Approval</p>
        <% if @accountabuddy_requests %>
              <% @accountabuddy_requests.each do |request| %>

                <% if request.friendship.accountabuddy == true %>
                <% else %>
                  <% if request.user.id == current_user.id %>
                  <% else %>
                    <li><%= request.user.name %></li>
                      <%= form_tag accountabuddy_request_path(request.id), method: 'put' do %>
                      <span><%= submit_tag "Accept", :class => "mySmallButton" %></span>
                      <% end %>
                    <% end %>
                <% end %>
              <% end %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
</div>