config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :friendships
  resources :categories
  resources :friend_requests, only: [:create, :update]
  resources :conversations
  resources :messages
  resources :badges
  resources :accountabuddy_requests, only:[:create, :update]
  resources :user_categories
  resources :recommendations, only:[:create, :new]
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  root 'users#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1 id="home-nav-bar"><%= link_to 'AccountaBuddy', user_path(current_user.id) %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <div id="right-nav" style="float:right;margin-right:2em;"> 
      <span style="color:white"> <%= link_to 'Profile', user_path(current_user.id) %> | <%= link_to "Start a new goal", categories_path %> | <%= link_to 'Logout', '/logout' %> | <%= link_to 'Edit Account', edit_user_path(current_user.id) %></span>
    </div>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta charset=utf-8 />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "AccountaBuddy" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="https://api.tiles.mapbox.com/mapbox.js/v1.0.2/mapbox.js"></script>
  <script src="https://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
  <link href="https://api.tiles.mapbox.com/mapbox.js/v1.0.2/mapbox.css" rel="stylesheet" />

  <%= csrf_meta_tags %>
</head>
<body>
  <header>

  </header>



<%= yield %>

</body>
</html>